# Generated by Django 3.2.3 on 2021-06-11 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedatecolumn',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_created=True)),
                ('appointment_date', models.DateTimeField()),
                ('time_slot', models.PositiveSmallIntegerField(choices=[(0, '9:00AM - 1:00PM'), (1, '1:00PM - 6:00PM')])),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to=settings.AUTH_USER_MODEL)),
                ('participent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
